WITH CTE1 AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = 'SUV' OR CAR_TYPE = '세단'
),
CTE2 AS (
    SELECT Y.CAR_ID, Y.CAR_TYPE, Y.DAILY_FEE * 30 * (1 - X.DISCOUNT_RATE / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN X
    JOIN CTE1 Y
    ON X.CAR_TYPE = Y.CAR_TYPE 
    WHERE X.DURATION_TYPE = '30일 이상' 
)
SELECT X.CAR_ID, X.CAR_TYPE, FLOOR(X.FEE) FEE
FROM CTE2 X 
WHERE X.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' 
    AND END_DATE >= '2022-11-01'
)
AND X.FEE >= 500000 AND X.FEE < 2000000
ORDER BY FEE DESC, X.CAR_TYPE ASC, X.CAR_ID DESC;
