WITH CTE AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
)
SELECT X.REST_ID, X.REST_NAME, X.FOOD_TYPE, X.FAVORITES, X.ADDRESS, Y.SCORE
FROM REST_INFO X
JOIN CTE Y
ON X.REST_ID = Y.REST_ID
WHERE X.ADDRESS LIKE '서울%'
ORDER BY Y.SCORE DESC, X.FAVORITES DESC
