WITH CTE AS (
    SELECT X.USER_ID, YEAR(X.SALES_DATE) as YEAR, MONTH(X.SALES_DATE) as MONTH, Y.GENDER
    FROM ONLINE_SALE X
    LEFT JOIN USER_INFO Y
    ON X.USER_ID = Y.USER_ID
    WHERE Y.GENDER IS NOT NULL
)
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) as USERS
FROM CTE
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;