WITH CTE1 AS (
    SELECT X.EMP_NO, X.EMP_NAME, Y.HALF_YEAR, Y.SCORE
    FROM HR_EMPLOYEES X
    LEFT JOIN HR_GRADE Y
    ON X.EMP_NO = Y.EMP_NO
),
CTE2 AS (
    SELECT X.EMP_NO, X.EMP_NAME, AVG(X.score) as SCORE
    FROM CTE1 X
    GROUP BY X.EMP_NO
),
CTE3 AS (
    SELECT X.EMP_NO, X.EMP_NAME, Y.SAL,
    CASE 
        WHEN X.SCORE >= 96 THEN 'S'
        WHEN X.SCORE >= 90 THEN 'A'
        WHEN X.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE
    FROM CTE2 X
    LEFT JOIN HR_EMPLOYEES Y
    ON X.EMP_NO = Y.EMP_NO
)
SELECT EMP_NO, EMP_NAME, GRADE,
CASE
    WHEN GRADE = 'S' THEN SAL*0.2
    WHEN GRADE = 'A' THEN SAL*0.15
    WHEN GRADE = 'B' THEN SAL*0.1
    ELSE 0
END AS BONUS
from CTE3
