WITH CTE AS (
    SELECT FISH_TYPE, MAX(LENGTH) as MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
),
CTE2 AS (
    SELECT X.FISH_TYPE, X.MAX_LEN, Y.FISH_NAME
    FROM CTE X
    LEFT JOIN FISH_NAME_INFO Y
    ON X.FISH_TYPE = Y.FISH_TYPE
),
CTE3 AS (
    SELECT X.ID, X.FISH_TYPE, X.LENGTH, Y.MAX_LEN, Y.FISH_NAME
    FROM FISH_INFO X
    JOIN CTE2 Y
    ON X.FISH_TYPE = Y.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM CTE3
WHERE LENGTH = MAX_LEN
ORDER BY ID ASC