WITH CTE AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD X
    WHERE X.VIEWS IN 
    (SELECT MAX(VIEWS) as MAX_VIEW
    FROM USED_GOODS_BOARD)
)
SELECT concat('/home/grep/src/',BOARD_ID,'/', FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE X
WHERE X.BOARD_ID IN
(
    SELECT BOARD_ID
    FROM CTE
)
ORDER BY FILE_ID DESC